const $=s=>document.querySelector(s);const app=$('#app');let typingTimer=null;
const animals=[['🐶','강아지'],['🐱','고양이'],['🐰','토끼'],['🦁','사자'],['🐯','호랑이'],['🐼','판다'],['🐘','코끼리'],['🦒','기린'],['🐵','원숭이'],['🦊','여우'],['🐻','곰'],['🐧','펭귄'],['🦉','부엉이'],['🐿️','다람쥐'],['🐳','고래'],['🐬','돌고래'],['🐢','거북이'],['🐙','문어'],['🐥','병아리'],['🐸','개구리']];
const seedStudents=[{id:1,school:'별빛초등학교',grade:2,room:'2학년 1반',name:'김민준',code:[0,2,5],active:true},{id:2,school:'별빛초등학교',grade:2,room:'2학년 1반',name:'이서윤',code:[3,8,12],active:true},{id:3,school:'별빛초등학교',grade:3,room:'3학년 2반',name:'박지호',code:[6,1,15],active:true}];
const defaults={students:seedStudents,schools:[],classes:[],records:[],settings:{sound:true,large:false,reduced:false}};
let state=JSON.parse(localStorage.getItem('tadakState')||'null')||structuredClone(defaults);let session={student:null,studentCode:null,adminPassword:null,role:null,login:{school:'',room:'',name:'',code:[]},practice:null,game:null,roomId:null,playerId:null};let composing=false,roomCache={},roomPoll=null,sharedReady=false;
const save=()=>localStorage.setItem('tadakState',JSON.stringify(state));
const roomText=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function dataRequest(payload){let response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json().catch(()=>({error:'공용 데이터 응답을 읽지 못했어요.'}));if(!response.ok)throw new Error(data.error||'공용 데이터에 연결하지 못했어요.');return data}
async function loadSharedData(){let data=await dataRequest({action:'bootstrap'});state.students=data.students.map(s=>({...s,id:Number(s.id)}));state.schools=data.schools||[];state.classes=data.classes||[];boardWords=data.words;sharedReady=true;save();return data}
function animalAvatar(index,size='normal'){let col=index%5,row=Math.floor(index/5);return `<span class="animal-avatar ${size}" style="--animal-x:${col};--animal-y:${row}" aria-hidden="true"></span>`}
function layout(content,opts={}){document.body.className=session.role==='admin'?'admin-mode':'student-mode';app.innerHTML=`<main id="main" class="shell"><header class="topbar"><button class="brand" style="border:0;background:none;color:inherit" onclick="go('${session.role==='admin'?'admin':'home'}')"><span class="brand-mark">⌨️</span><span>타닥타닥 탐험대</span></button><div class="top-actions">${session.student?`<span class="pill">🌟 ${session.student.name} · ${session.student.room}</span>`:''}${session.role?`<button class="btn" onclick="logout()">나가기</button>`:''}</div></header>${content}</main>`}
function go(view,arg){if(view!=='typing'&&typingTimer){clearInterval(typingTimer);typingTimer=null}if(!['roomLobby','roomView','roomGame'].includes(view)&&roomPoll){clearInterval(roomPoll);roomPoll=null}({start,login,home,practice,typing,gameMenu,board,roomLobby,roomView,roomGame,mouse,records,settings,result,admin,organizations,students,words}[view]||start)(arg);scrollTo(0,0)}
function start(){session.role=null;session.student=null;layout(`<section class="hero"><div class="panel"><span class="eyebrow">놀면서 배우는 첫 컴퓨터 여행</span><h1>한 글자씩,<br>신나게 출발!</h1><p>정확하게 누를수록 탐험 지도가 반짝여요. 타자와 마우스를 차근차근 익혀 보세요.</p><div class="row"><button class="btn primary" onclick="go('login')">🚀 학생으로 시작하기</button><button class="btn" onclick="adminLogin()">선생님·관리자</button></div></div><div class="panel mascot"><div><div class="tadaki" aria-label="키보드 배를 가진 하늘색 별 캐릭터"><span>★</span><b>⌨</b></div><h2>타닥이와 같이 탐험할까?</h2><p style="color:#fff">천천히 정확하게 눌러 보자!</p></div></div></section><section class="choice-grid section-title"><div class="card choice typing-card"><div class="icon">⌨️</div><h3>타자연습</h3><p>자리부터 문장까지 차근차근!</p></div><div class="card choice game-card"><div class="icon">🎮</div><h3>타자게임</h3><p>단어를 입력하고 게임에 도전!</p></div><div class="card choice mouse-card"><div class="icon">🖱️</div><h3>마우스놀이</h3><p>움직이고 누르며 마우스와 친해지기!</p></div></section>`)}
function login(){let l=session.login,step=!l.school?1:!l.room?2:!l.name?3:4;let students=state.students.filter(s=>s.active);let body='';if(step===1){body=`<div class="field"><label for="school">학교를 골라 주세요</label><select id="school"><option value="">학교 선택</option>${[...new Set(students.map(s=>s.school))].map(x=>`<option>${x}</option>`)}</select></div><button class="btn primary" onclick="pick('school')">다음</button>`}if(step===2){body=`<button class="btn" onclick="resetLogin(1)">← 학교 다시 고르기</button><div class="field"><label for="room">우리 반을 골라 주세요</label><select id="room"><option value="">반 선택</option>${[...new Set(students.filter(s=>s.school===l.school).map(s=>s.room))].map(x=>`<option>${x}</option>`)}</select></div><button class="btn primary" onclick="pick('room')">다음</button>`}if(step===3){body=`<button class="btn" onclick="resetLogin(2)">← 반 다시 고르기</button><div class="field"><label for="name">내 이름을 골라 주세요</label><select id="name"><option value="">이름 선택</option>${students.filter(s=>s.school===l.school&&s.room===l.room).map(s=>`<option>${s.name}</option>`)}</select></div><button class="btn primary" onclick="pick('name')">다음</button>`}if(step===4){body=`<p><b>${l.name}</b> 탐험가의 동물 3마리를 순서대로 눌러 주세요.</p><div class="selected-code animal-code-preview">${l.code.length?l.code.map(i=>animalAvatar(i,'small')).join(''):'<span class="code-empty">○ ○ ○</span>'}</div><div class="animal-grid">${animals.map((a,i)=>`<button class="animal ${l.code.includes(i)?'selected':''}" aria-label="${a[1]}" onclick="animalPick(${i})">${animalAvatar(i)}<b>${a[1]}</b></button>`).join('')}</div><div class="row" style="margin-top:18px"><button class="btn" onclick="session.login.code=[];login()">모두 지우기</button><button class="btn primary" onclick="studentLogin()" ${l.code.length!==3?'disabled':''}>탐험 시작!</button></div>`}layout(`<section class="panel login-box"><div class="steps">${[1,2,3,4].map(i=>`<i class="step ${i<=step?'on':''}"></i>`).join('')}</div><span class="eyebrow">${step}/4 단계</span><h1>반가워요! 누구인가요?</h1>${body}</section>`)}
function pick(k){let v=$('#'+k).value;if(!v)return;session.login[k]=v;login()}function resetLogin(n){if(n<3)session.login.name='';if(n<2)session.login.room='';if(n<1)session.login.school='';session.login.code=[];login()}function animalPick(i){if(session.login.code.includes(i)||session.login.code.length===3)return;session.login.code.push(i);login()}
function studentLogin(){let l=session.login,s=state.students.find(s=>s.school===l.school&&s.room===l.room&&s.name===l.name&&s.code.join()==l.code.join());if(!s){alert('동물 순서가 맞지 않아요. 천천히 다시 해 볼까요?');l.code=[];return login()}session.student=s;session.role='student';go('home')}
function home(){let r=state.records.filter(x=>x.studentId===session.student.id),best=Math.max(0,...r.map(x=>x.cpm||0)),avg=r.length?Math.round(r.reduce((a,b)=>a+(b.accuracy||0),0)/r.length):0;layout(`<section class="panel welcome"><span class="eyebrow">오늘의 탐험</span><h1>${session.student.name}아, 오늘도 반가워! 👋</h1><p class="muted">오늘은 전체자리 낱말 탐험으로 별 하나를 채워 볼까?</p><div class="stats"><div class="stat"><strong>${best}</strong>최고 타수</div><div class="stat"><strong>${avg}%</strong>평균 정확도</div><div class="stat"><strong>${r.length}회</strong>총 연습</div></div><button class="btn primary" onclick="startTyping('낱말연습','전체자리')">🚀 추천 연습 시작!</button></section><div class="section-title playful-title"><h2>어디로 탐험할까요?</h2><span class="muted">마음 가는 곳을 콕!</span></div><section class="cards home-menu"><button class="card typing-card" onclick="go('practice')"><div class="icon">⌨️</div><span class="scribble">STEP BY STEP</span><h3>타자연습</h3><p>손가락·낱말·긴글을 차근차근!</p></button><button class="card game-card" onclick="go('gameMenu')"><div class="icon">🎮</div><span class="scribble">PLAY!</span><h3>타자게임</h3><p>혼자 또는 친구와 팀을 나눠 도전!</p></button><button class="card mouse-card" onclick="go('mouse')"><div class="icon">🖱️</div><span class="scribble">CLICK!</span><h3>마우스놀이</h3><p>움직이고 누르며 마우스와 친해지기!</p></button></section><div class="section-title playful-title"><h2>나의 탐험 노트</h2></div><section class="cards compact-cards scrapbook"><button class="card" onclick="go('records')"><div class="icon">📈</div><h3>나의 기록</h3><p>조금씩 자라는 나를 확인해요</p></button><button class="card" onclick="go('settings')"><div class="icon">⚙️</div><h3>설정</h3><p>소리와 글자 크기를 바꿔요</p></button></section>`)}
function practice(mode){if(!mode)return layout(`<div class="section-title"><div><span class="eyebrow">타자연습</span><h1>어떤 연습을 시작할까요?</h1><p class="muted">손가락 위치부터 긴 글까지 차근차근 익혀요.</p></div><button class="btn" onclick="go('home')">← 홈</button></div><section class="cards practice-types"><button class="card typing-card" onclick="go('practice','finger')"><div class="icon">🙌</div><span class="card-tag">자리별 선택</span><h3>손가락연습</h3><p>각 키를 담당하는 손가락과 자리를 익혀요.</p></button><button class="card typing-card" onclick="go('practice','word')"><div class="icon">🍎</div><span class="card-tag">자리별 선택</span><h3>낱말연습</h3><p>자리별 핵심 글쇠가 들어간 낱말을 연습해요.</p></button><button class="card typing-card" onclick="startTyping('긴글연습','긴글')"><div class="icon">📖</div><span class="card-tag long">120초</span><h3>긴글연습</h3><p>긴 문장을 이어 입력하며 집중력과 속도를 길러요.</p></button></section>`);let title=mode==='finger'?'손가락연습':'낱말연습',desc=mode==='finger'?'연습할 키보드 자리를 골라 주세요.':'집중해서 연습할 자리를 골라 주세요.';layout(`<div class="section-title"><div><span class="eyebrow">${title}</span><h1>${desc}</h1><p class="muted">왼손과 오른손을 나눠 연습한 뒤 전체자리로 도전해요.</p></div><button class="btn" onclick="go('practice')">← 연습 종류</button></div><section class="lesson-grid">${lessonOrder.map((level,i)=>`<button class="card lesson-card" onclick="startTyping('${title}','${level}')"><span class="lesson-no">${i+1}</span><div class="icon">${lessonIcons[i]}</div><h3>${level}</h3><p>${lessonDescriptions[mode][level]}</p><span class="lesson-go">연습 시작 →</span></button>`).join('')}</section>`)}
const lessonOrder=['기본자리','왼손 윗자리','왼손 아랫자리','오른손 윗자리','오른손 아랫자리','전체자리'];
const lessonIcons=['🏠','↖️','↙️','↗️','↘️','⌨️'];
const lessonDescriptions={finger:{'기본자리':'ㅁ ㄴ ㅇ ㄹ · ㅓ ㅏ ㅣ','왼손 윗자리':'ㅂ ㅈ ㄷ ㄱ ㅅ','왼손 아랫자리':'ㅋ ㅌ ㅊ ㅍ ㅠ','오른손 윗자리':'ㅛ ㅕ ㅑ ㅐ ㅔ','오른손 아랫자리':'ㅜ ㅡ · 쉼표와 마침표','전체자리':'모든 글쇠를 골고루'},word:{'기본자리':'마음 · 나라 · 사랑','왼손 윗자리':'토끼 · 따뜻한 · 기차','왼손 아랫자리':'친구 · 피자 · 우표','오른손 윗자리':'우유 · 여우 · 이야기','오른손 아랫자리':'나무 · 구름 · 바나나','전체자리':'학교 · 고양이 · 무지개'}};
const lessonSets={
 '손가락연습':{'기본자리':['ㅁ','ㄴ','ㅇ','ㄹ','ㅓ','ㅏ','ㅣ'],'왼손 윗자리':['ㅂ','ㅈ','ㄷ','ㄱ','ㅅ'],'왼손 아랫자리':['ㅋ','ㅌ','ㅊ','ㅍ','ㅠ'],'오른손 윗자리':['ㅛ','ㅕ','ㅑ','ㅐ','ㅔ'],'오른손 아랫자리':['ㅜ','ㅡ','ㅜ','ㅡ'],'전체자리':['ㅁ','ㅂ','ㅋ','ㄴ','ㅈ','ㅌ','ㅇ','ㄷ','ㅊ','ㄹ','ㄱ','ㅍ','ㅎ','ㅅ','ㅠ','ㅛ','ㅗ','ㅓ','ㅜ','ㅏ','ㅡ','ㅣ']},
 '낱말연습':{'기본자리':['마음','나라','사랑','아리랑'],'왼손 윗자리':['토끼','따뜻한','기차','다섯'],'왼손 아랫자리':['친구','피자','우표','치마'],'오른손 윗자리':['우유','여우','이야기','예쁘다'],'오른손 아랫자리':['나무','구름','바나나','무지개'],'전체자리':['학교','고양이','친구','하늘','바다','컴퓨터']},
 '긴글연습':{'긴글':['맑은 아침 햇살이 교실 창문으로 들어왔어요. 친구들은 서로 반갑게 인사하고 오늘 배울 내용을 기대했어요.','천천히 정확하게 글자를 입력하면 손가락이 키보드 자리를 기억해요. 매일 조금씩 연습하면 어느새 빠르고 편안하게 글을 쓸 수 있어요.','푸른 하늘 아래에서 아이들이 신나게 뛰어놀았어요. 웃음소리가 운동장에 가득 퍼지고 모두의 마음도 밝아졌어요.']}
};
const keyboardRows=[[['`','`','l-pinky'],['1','1','l-pinky'],['2','2','l-ring'],['3','3','l-middle'],['4','4','l-index'],['5','5','l-index'],['6','6','r-index'],['7','7','r-index'],['8','8','r-middle'],['9','9','r-ring'],['0','0','r-pinky'],['-','-','r-pinky'],['=','=','r-pinky'],['Backspace','지우기','r-pinky',2]],[['Tab','Tab','l-pinky',1.45],['q','ㅂ','l-pinky'],['w','ㅈ','l-ring'],['e','ㄷ','l-middle'],['r','ㄱ','l-index'],['t','ㅅ','l-index'],['y','ㅛ','r-index'],['u','ㅕ','r-index'],['i','ㅑ','r-middle'],['o','ㅐ','r-ring'],['p','ㅔ','r-pinky'],['[','[','r-pinky'],[']',']','r-pinky'],['\\','\\','r-pinky',1.45]],[['CapsLock','Caps','l-pinky',1.7],['a','ㅁ','l-pinky'],['s','ㄴ','l-ring'],['d','ㅇ','l-middle'],['f','ㄹ','l-index'],['g','ㅎ','l-index'],['h','ㅗ','r-index'],['j','ㅓ','r-index'],['k','ㅏ','r-middle'],['l','ㅣ','r-ring'],[';',';','r-pinky'],["'","'",'r-pinky'],['Enter','Enter','r-pinky',2.05]],[['Shift','Shift','l-pinky',2.15],['z','ㅋ','l-pinky'],['x','ㅌ','l-ring'],['c','ㅊ','l-middle'],['v','ㅍ','l-index'],['b','ㅠ','l-index'],['n','ㅜ','r-index'],['m','ㅡ','r-index'],[',',',','r-middle'],['.','.','r-ring'],['/','/','r-pinky'],['ShiftRight','Shift','r-pinky',2.55]],[['Control','Ctrl','l-pinky',1.2],['Meta','Win','l-pinky',1.15],['Alt','Alt','thumb',1.15],[' ','SPACE','thumb',6.4],['AltGraph','한/영','thumb',1.25],['ContextMenu','메뉴','r-pinky',1.1],['ControlRight','Ctrl','r-pinky',1.2]]];
const shiftedKeys={q:'ㅃ',w:'ㅉ',e:'ㄸ',r:'ㄲ',t:'ㅆ',o:'ㅒ',p:'ㅖ','`':'~','1':'!','2':'@','3':'#','4':'$','5':'%','6':'^','7':'&','8':'*','9':'(','0':')','-':'_','=':'+'};
function keyboardMarkup(){return `<div class="keyboard-stage"><div class="full-keyboard">${keyboardRows.map(row=>`<div class="key-row">${row.map(([key,label,finger,width=1])=>{let korean=/^[a-z]$/.test(key),home=['a','s','d','f','j','k','l',';'].includes(key);return `<span class="full-key ${home?'home-position ':''}${['f','j'].includes(key)?'home-key':''}" data-key="${key}" data-finger="${finger}" style="--wide:${width}">${korean?`<i class="en">${key}</i><b class="ko">${label}</b>${shiftedKeys[key]?`<i class="shifted">${shiftedKeys[key]}</i>`:''}`:`<b class="plain-label">${label}</b>`}</span>`}).join('')}</div>`).join('')}</div><div class="sprite-hands" id="spriteHands" aria-hidden="true"></div></div>`}
function startTyping(type,level){let source=lessonSets[type]?.[level]||lessonSets['낱말연습']['전체자리'],items=type==='긴글연습'?[...source]:[...source,...source],limit=type==='긴글연습'?120:60;session.practice={type,level,items,idx:0,correct:0,errors:0,typed:0,lastWrong:0,start:null,limit,remaining:limit,running:false};typing()}
function sentenceMarkup(target,typed=''){return [...target].map((ch,i)=>{let cls=i<typed.length?(typed[i]===ch?'done':'wrong'):(i===typed.length?'current':'rest');return `<span class="${cls}">${ch===' '?'&nbsp;':ch}</span>`}).join('')}
function typing(){let p=session.practice,target=p.items[p.idx%p.items.length],pct=p.idx/p.items.length*100;layout(`<section class="speed-game"><div class="speed-top"><button class="btn" onclick="go('practice','${p.type==='손가락연습'?'finger':p.type==='낱말연습'?'word':''}')">← 나가기</button><div><span class="eyebrow">${p.type} · ${p.level}</span><h1>정확하게, 그리고 빠르게!</h1></div><button class="btn" onclick="pauseTyping()">${p.running?'Ⅱ 잠깐 멈추기':'▶ 이어하기'}</button></div><div class="speed-hud"><div class="hud-item"><span>현재 타수</span><strong id="liveCpm">0</strong><small>타/분</small></div><div class="hud-item"><span>정확도</span><strong id="liveAccuracy">100</strong><small>%</small></div><div class="hud-item timer"><span>남은 시간</span><strong id="liveTime">${p.remaining}</strong><small>초</small></div><div class="hud-item"><span>완료 문제</span><strong id="liveCount">${p.idx}</strong><small>개</small></div></div><section class="panel speed-stage ${p.type==='긴글연습'?'long-stage':''}"><div class="speed-progress"><span>${p.idx+1}번째 문제</span><div class="progress"><b style="width:${Math.min(100,pct)}%"></b></div></div><p class="muted">보이는 내용을 아래 입력창에 똑같이 입력하세요.</p><div id="speedSentence" class="sentence" aria-label="연습 내용 ${target}">${sentenceMarkup(target)}</div><input id="typeInput" class="type-input speed-input" autocomplete="off" spellcheck="false" aria-label="타자 입력" placeholder="시작 버튼을 누르면 입력할 수 있어요" ${p.running?'':'disabled'} oncompositionstart="composing=true" oncompositionend="composing=false;checkTyping(event)" oninput="checkTyping(event)">${!p.start?`<button class="btn primary speed-start" onclick="beginTyping()">🚀 연습 시작</button>`:''}<p class="keyboard-guide">누르는 키와 움직이는 손 위치를 확인해 보세요.</p>${keyboardMarkup()}<div id="typingMessage" class="notice">💡 틀린 글자는 빨간색으로 보여요. Backspace로 고쳐 보세요.</div></section></section>`);showSpritePose('base');if(p.running)setTimeout(()=>$('#typeInput')?.focus(),0)}
function beginTyping(){let p=session.practice;if(!p.start)p.start=Date.now();p.running=true;if(typingTimer)clearInterval(typingTimer);typingTimer=setInterval(tickTyping,1000);typing()}
function pauseTyping(){let p=session.practice;if(!p.start)return beginTyping();p.running=!p.running;if(p.running){typingTimer=setInterval(tickTyping,1000)}else{clearInterval(typingTimer);typingTimer=null}typing()}
function tickTyping(){let p=session.practice;if(!p?.running)return;p.remaining--;let time=$('#liveTime');if(time)time.textContent=p.remaining;updateSpeedStats();if(p.remaining<=0){clearInterval(typingTimer);typingTimer=null;p.running=false;finish(`${p.type} 속도게임`)}}
function updateSpeedStats(){let p=session.practice,sec=Math.max(1,p.limit-p.remaining),cpm=Math.round(p.correct/sec*60),acc=Math.round(p.correct/(p.typed||1)*100);if($('#liveCpm'))$('#liveCpm').textContent=cpm;if($('#liveAccuracy'))$('#liveAccuracy').textContent=acc;if($('#liveCount'))$('#liveCount').textContent=p.idx}
function checkTyping(e){if(composing)return;let p=session.practice,target=p.items[p.idx%p.items.length],v=e.target.value;p.typed++;let wrong=[...v].filter((c,i)=>c!==target[i]).length;if(wrong>p.lastWrong){p.errors++;p.lastWrong=wrong}else p.lastWrong=wrong;$('#speedSentence').innerHTML=sentenceMarkup(target,v);e.target.classList.toggle('error',wrong>0);let next=target[v.length]||'';document.querySelectorAll('.speed-keyboard .key').forEach(k=>k.classList.toggle('active',k.textContent===next));updateSpeedStats();if(v===target){p.correct+=target.length;p.idx++;p.lastWrong=0;$('#typingMessage').className='notice success';$('#typingMessage').textContent='✓ 정확해요! 다음 문장으로 넘어갈게요.';setTimeout(()=>typing(),260)}}
const codeToKey={Backquote:'`',Digit1:'1',Digit2:'2',Digit3:'3',Digit4:'4',Digit5:'5',Digit6:'6',Digit7:'7',Digit8:'8',Digit9:'9',Digit0:'0',Minus:'-',Equal:'=',KeyQ:'q',KeyW:'w',KeyE:'e',KeyR:'r',KeyT:'t',KeyY:'y',KeyU:'u',KeyI:'i',KeyO:'o',KeyP:'p',BracketLeft:'[',BracketRight:']',Backslash:'\\',KeyA:'a',KeyS:'s',KeyD:'d',KeyF:'f',KeyG:'g',KeyH:'h',KeyJ:'j',KeyK:'k',KeyL:'l',Semicolon:';',Quote:"'",KeyZ:'z',KeyX:'x',KeyC:'c',KeyV:'v',KeyB:'b',KeyN:'n',KeyM:'m',Comma:',',Period:'.',Slash:'/',Space:' ',ShiftLeft:'Shift',ShiftRight:'ShiftRight',ControlLeft:'Control',ControlRight:'ControlRight',AltLeft:'Alt',AltRight:'AltGraph',MetaLeft:'Meta',ContextMenu:'ContextMenu',Backspace:'Backspace',Enter:'Enter'};
const spriteKeys=['base',...'qwertyuiopasdfghjkl;zxcvbnm,.'];
function showSpritePose(key='base'){let el=$('#spriteHands');if(!el)return;let normalized=key.length===1?key.toLowerCase():'base',index=Math.max(0,spriteKeys.indexOf(normalized)),col=index%6,row=Math.floor(index/6);el.style.backgroundPosition=`${col*20}% ${row*25}%`}
function showPhysicalKey(e,down){if(!$('#spriteHands'))return;let key=codeToKey[e.code]||(e.key.length===1?e.key.toLowerCase():e.key),el=document.querySelector(`.full-key[data-key="${CSS.escape(key)}"]`);if(el)el.classList.toggle('pressed',down);if(down)showSpritePose(key);else setTimeout(()=>showSpritePose('base'),50)}
document.addEventListener('keydown',e=>showPhysicalKey(e,true));document.addEventListener('keyup',e=>showPhysicalKey(e,false));
async function recordRequest(payload){let response=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json().catch(()=>({error:'기록 서버 응답을 읽지 못했어요.'}));if(!response.ok)throw new Error(data.error||'기록 서버에 연결하지 못했어요.');return data}
const studentProof=()=>({id:session.student.id,name:session.student.name,code:session.studentCode});
const mapRemoteRecord=row=>({clientId:row.client_id,studentId:Number(row.student_id),type:row.activity_type,accuracy:row.accuracy,cpm:row.cpm,score:row.score,date:new Date(row.created_at).toLocaleDateString('ko-KR'),...(row.details||{})});
async function syncStudentRecords(){if(!session.student)return;let data=await recordRequest({action:'studentRecords',student:studentProof()}),remote=data.records.map(mapRemoteRecord),others=state.records.filter(r=>r.studentId!==session.student.id),local=state.records.filter(r=>r.studentId===session.student.id&&!r.clientId),seen=new Set();state.records=[...others,...remote,...local].filter(r=>!r.clientId||(!seen.has(r.clientId)&&seen.add(r.clientId)));save()}
async function syncAdminRecords(){let data=await recordRequest({action:'adminRecords',password:session.adminPassword}),remote=data.records.map(mapRemoteRecord),local=state.records.filter(r=>!r.clientId),seen=new Set();state.records=[...remote,...local].filter(r=>!r.clientId||(!seen.has(r.clientId)&&seen.add(r.clientId)));save()}
function finish(type,extra={}){let p=session.practice||{correct:10,errors:0,start:Date.now()-60000},sec=Math.max(10,(Date.now()-p.start)/1000),acc=Math.round(p.correct/(p.correct+p.errors||1)*100),cpm=Math.round(p.correct/sec*60),score=Math.round(acc*5+cpm*2),clientId=globalThis.crypto?.randomUUID?.()||`${session.student.id}-${Date.now()}-${Math.random()}`;let rec={clientId,studentId:session.student.id,type,accuracy:acc,cpm,score,date:'오늘',...extra};state.records.unshift(rec);save();recordRequest({action:'save',student:studentProof(),record:{...rec,details:extra}}).catch(()=>{});session.last=rec;go('result')}
function result(){let r=session.last,stars=r.accuracy>=95?'⭐⭐⭐':r.accuracy>=85?'⭐⭐':'⭐';layout(`<section class="panel practice"><div class="result-medal">🏅</div><span class="eyebrow">탐험 완료!</span><h1>정확하게 끝까지 해냈어요</h1><div style="font-size:46px">${stars}</div><div class="stats"><div class="stat"><strong>${r.accuracy}%</strong>정확도</div><div class="stat"><strong>${r.cpm||'-'}</strong>분당 타수</div><div class="stat"><strong>${r.score}</strong>점수</div></div><p class="notice success">지난번보다 한 걸음 더 자랐어요. 정확한 입력이 가장 멋져요!</p><div class="row" style="justify-content:center"><button class="btn" onclick="go('records')">기록 보기</button><button class="btn primary" onclick="go('home')">홈으로</button></div></section>`)}
function gameMenu(){layout(`<div class="section-title"><div><span class="eyebrow">타자게임</span><h1>어떻게 게임할까요?</h1><p class="muted">혼자 연습하거나 친구들과 두 팀으로 나눠 함께할 수 있어요.</p></div><button class="btn" onclick="go('home')">← 홈</button></div><section class="game-mode-grid"><button class="card solo-mode" onclick="go('board')"><div class="mode-art">🧑‍🚀</div><span class="card-tag">혼자 하기</span><h2>컴퓨터와 판뒤집기</h2><p>내 속도로 연습하며 컴퓨터 팀과 겨뤄요.</p><span class="lesson-go">바로 시작 →</span></button><button class="card together-mode" onclick="go('roomLobby')"><div class="mode-art">👧🏻 👦🏻</div><span class="card-tag">함께 하기</span><h2>친구들과 팀 대결</h2><p>방을 만들거나 코드로 입장하고, 구름팀과 별팀으로 나눠요.</p><span class="lesson-go">방 찾기 →</span></button></section>`)}
function getRooms(){return roomCache}
async function roomRequest(path='',options={}){let response=await fetch(`/api/rooms${path}`,{headers:{'Content-Type':'application/json'},...options});let data=await response.json().catch(()=>({error:'방 서버 응답을 읽지 못했어요.'}));if(!response.ok)throw new Error(data.error||'방 서버에 연결하지 못했어요.');return data}
function roomCards(rooms){return rooms.length?rooms.map(r=>`<button class="card room-card" onclick="joinRoom('${r.code}')"><span class="room-code">${r.code}</span><h3>${roomText(r.title)}</h3><p>👥 ${r.players.length}명 · ${r.players.length%2===0?'시작 가능':'한 명 더 필요해요'}</p></button>`).join(''):`<div class="panel empty">아직 기다리는 방이 없어요.<br>첫 번째 방을 만들어 볼까요?</div>`}
async function refreshLobby(){try{let rooms=await roomRequest();roomCache=Object.fromEntries(rooms.map(r=>[r.code,r]));let list=$('.room-list'),count=$('.room-count');if(list)list.innerHTML=roomCards(rooms);if(count)count.textContent=`${rooms.length}개`}catch(error){let list=$('.room-list');if(list)list.innerHTML=`<div class="panel empty">${error.message}<br>잠시 후 다시 시도해 주세요.</div>`}}
function beginRoomPoll(mode){if(roomPoll)clearInterval(roomPoll);roomPoll=setInterval(async()=>{if(!session.roomId)return;try{let remote=await roomRequest(`/${session.roomId}`),before=JSON.stringify(roomCache[session.roomId]);roomCache[remote.code]=remote;if(JSON.stringify(remote)!==before)(remote.status==='playing'?roomGame:roomView)(false)}catch(error){if(error.message.includes('찾을')){session.roomId=null;session.playerId=null;go('roomLobby')}}},800)}
async function createRoom(){let button=$('.create-room .btn');button&&(button.disabled=true);try{let title=$('#roomTitle')?.value.trim()||`${session.student.name}의 방`,pid=`${session.student.id}-${Date.now()}`,room=await roomRequest('',{method:'POST',body:JSON.stringify({title,player:{id:pid,name:session.student.name}})});roomCache[room.code]=room;session.roomId=room.code;session.playerId=pid;roomView()}catch(error){alert(error.message);button&&(button.disabled=false)}}
async function joinRoom(code){code=(code||$('#roomCode')?.value||'').trim().toUpperCase();if(!code)return alert('방 코드를 입력해 주세요.');let pid=`${session.student.id}-${Date.now()}`;try{let room=await roomRequest(`/${code}/action`,{method:'POST',body:JSON.stringify({action:'join',player:{id:pid,name:session.student.name}})});roomCache[room.code]=room;session.roomId=code;session.playerId=pid;roomView()}catch(error){alert(error.message)}}
function roomLobby(){if(roomPoll)clearInterval(roomPoll);layout(`<div class="section-title"><div><span class="eyebrow">함께 하기</span><h1>친구들과 만날 방을 골라요</h1></div><button class="btn" onclick="go('gameMenu')">← 게임 선택</button></div><section class="room-actions"><div class="panel create-room"><div class="mode-art">🏠</div><h2>새 방 만들기</h2><div class="field"><label for="roomTitle">방 이름</label><input id="roomTitle" maxlength="20" value="${session.student.name}의 신나는 방"></div><button class="btn primary" onclick="createRoom()">+ 방 만들기</button></div><div class="panel join-room"><div class="mode-art">🎟️</div><h2>방 코드로 입장</h2><div class="field"><label for="roomCode">4자리 방 코드</label><input id="roomCode" maxlength="4" placeholder="예: STAR" style="text-transform:uppercase"></div><button class="btn mint" onclick="joinRoom()">방에 입장하기</button></div></section><div class="section-title playful-title"><h2>지금 기다리는 방</h2><span class="muted room-count">불러오는 중</span></div><section class="room-list"><div class="panel empty">기다리는 방을 불러오고 있어요…</div></section>`);refreshLobby();roomPoll=setInterval(refreshLobby,1500)}
function currentRoom(){return roomCache[session.roomId]}
async function addDemoPlayer(){try{let r=await roomRequest(`/${session.roomId}/action`,{method:'POST',body:JSON.stringify({action:'demo'})});roomCache[r.code]=r;roomView()}catch(error){alert(error.message)}}
async function leaveRoom(){let code=session.roomId,pid=session.playerId;if(roomPoll){clearInterval(roomPoll);roomPoll=null}session.roomId=null;session.playerId=null;if(code&&pid)roomRequest(`/${code}/action`,{method:'POST',body:JSON.stringify({action:'leave',playerId:pid})}).catch(()=>{});go('roomLobby')}
async function startRoomGame(){let r=currentRoom();if(!r||r.host!==session.playerId)return;if(r.players.length<2||r.players.length%2)return alert('짝수 인원이 모여야 시작할 수 있어요.');try{r=await roomRequest(`/${r.code}/action`,{method:'POST',body:JSON.stringify({action:'start',playerId:session.playerId,words:boardWords})});roomCache[r.code]=r;roomGame()}catch(error){alert(error.message)}}
function roomView(startPolling=true){let r=currentRoom();if(!r){roomRequest(`/${session.roomId}`).then(remote=>{roomCache[remote.code]=remote;roomView()}).catch(()=>go('roomLobby'));return}if(r.status==='playing')return roomGame(startPolling);let even=r.players.length>=2&&r.players.length%2===0,isHost=r.host===session.playerId;layout(`<div class="room-head"><button class="btn" onclick="leaveRoom()">← 방 나가기</button><div><span class="eyebrow">방 코드 ${r.code}</span><h1>${roomText(r.title)}</h1></div><span class="room-status ${even?'ready':''}">${even?'✓ 시작할 수 있어요':'● 짝수 인원을 기다리는 중'}</span></div><section class="team-board"><div class="team cloud-team"><div class="team-title">☁️ 구름팀</div>${r.players.filter((_,i)=>i%2===0).map((p,i)=>`<div class="player ${p.id===r.host?'host':''}"><span>${['🐶','🐰','🐼','🦊'][i%4]}</span><b>${roomText(p.name)}</b>${p.id===r.host?'<small>방장</small>':''}</div>`).join('')}<div class="team-score">${Math.ceil(r.players.length/2)}명</div></div><div class="versus">VS</div><div class="team star-team"><div class="team-title">⭐ 별팀</div>${r.players.filter((_,i)=>i%2===1).map((p,i)=>`<div class="player"><span>${['🐱','🐯','🐵','🐧'][i%4]}</span><b>${roomText(p.name)}</b></div>`).join('')||'<div class="waiting-seat">친구를 기다려요</div>'}<div class="team-score">${Math.floor(r.players.length/2)}명</div></div></section><section class="panel room-footer"><p>${even?'양쪽 팀의 수가 같아요. 준비됐다면 시작해요!':'참가자가 짝수가 되면 게임을 시작할 수 있어요.'}</p><div class="row">${isHost?`<button class="btn" onclick="addDemoPlayer()">+ 체험 친구 추가</button><button class="btn primary" onclick="startRoomGame()" ${even?'':'disabled'}>🎮 팀 게임 시작</button>`:'<span class="notice">방장이 게임을 시작할 때까지 기다려 주세요.</span>'}</div></section>`);if(startPolling)beginRoomPoll('lobby')}
function roomGame(startPolling=true){let r=currentRoom();if(!r)return go('roomLobby');let meIndex=r.players.findIndex(p=>p.id===session.playerId),myTeam=meIndex%2===0?'cloud':'star',cloud=r.tiles.filter(t=>t.owner==='cloud').length;session.game={room:true,active:null,lastWrong:0,myTeam};layout(`<section class="panel practice"><div class="multiplayer-score"><div class="cloud-badge">☁️ 구름팀 <b>${cloud}</b></div><span>방 ${r.code}</span><div class="star-badge">⭐ 별팀 <b>${16-cloud}</b></div></div><h1>${myTeam==='cloud'?'구름팀':'별팀'} 단어를 바로 입력해요!</h1><p>상대 팀 단어를 입력하고 <b>Space</b>를 누르면 즉시 판이 뒤집혀요.</p><div class="board">${r.tiles.map((t,i)=>`<button class="tile ${t.owner}" data-word="${t.w}" onclick="selectRoomTile(${i})" ${t.owner===myTeam?'disabled':''}>${t.owner==='cloud'?'☁️':'⭐'}<br>${t.w}</button>`).join('')}</div>${boardEntry('','')}<input id="boardInput" class="type-input board-input" aria-label="상대 팀 단어 입력" placeholder="상대 팀 단어 입력 후 Space" oncompositionstart="composing=true" oncompositionend="composing=false" oninput="roomType(event)" onkeydown="roomKey(event)"><button class="btn" onclick="leaveRoom()">게임 나가기</button></section>`);setTimeout(()=>$('#boardInput')?.focus(),0);if(startPolling)beginRoomPoll('game')}
function selectRoomTile(i){let r=currentRoom(),target=r.tiles[i].w,input=$('#boardInput');session.game.active=i;input.value=target;input.classList.remove('error');$('.board-entry').outerHTML=boardEntry(target,target);input.focus();input.setSelectionRange(target.length,target.length);document.querySelectorAll('.board .tile').forEach((el,n)=>el.classList.toggle('active',n===i))}
function roomType(e){if(composing||e.isComposing)return;let r=currentRoom(),v=e.target.value.trim(),candidates=r.tiles.filter(t=>t.owner!==session.game.myTeam),candidate=candidates.find(t=>t.w.startsWith(v)&&v)||candidates.find(t=>t.w===v);updateBoardCandidate(candidate?.w||v,v)}
async function roomKey(e){if(e.code!=='Space'||composing||e.isComposing)return;e.preventDefault();let value=e.target.value.trim(),r=currentRoom(),tile=r.tiles.find(t=>t.owner!==session.game.myTeam&&t.w===value);if(!tile)return boardReject(e.target);tile.owner=session.game.myTeam;roomGame(false);try{let remote=await roomRequest(`/${r.code}/action`,{method:'POST',body:JSON.stringify({action:'flip',playerId:session.playerId,word:value,team:session.game.myTeam})});roomCache[remote.code]=remote;if(JSON.stringify(remote)!==JSON.stringify(r))roomGame(false)}catch(error){alert(error.message);let remote=await roomRequest(`/${r.code}`);roomCache[remote.code]=remote;roomGame(false)}}
let boardWords=['별','달','숲','꽃','바다','학교','친구','하늘','토끼','나무','노래','마음','여우','구름','사과','웃음'];
function board(){session.game={tiles:boardWords.map((w,i)=>({w,owner:i%3===0?'me':'cpu'})),active:null,start:Date.now(),correct:0,errors:0,lastWrong:0};renderBoard()}
function boardEntry(target='',value=''){return `<div class="board-entry ${target?'':'idle'}"><span class="entry-label">${target?'입력 중인 단어':'바로 입력할 수 있어요'}</span><div id="boardPreview" class="board-preview">${target?sentenceMarkup(target,value):'단어 + Space'}</div><small>${target?'Space를 누르면 바로 판정해요.':'상대편 판의 단어를 입력하고 Space를 누르세요.'}</small></div>`}
function renderBoard(){let g=session.game,me=g.tiles.filter(x=>x.owner==='me').length;layout(`<section class="panel practice"><div class="row" style="justify-content:space-between"><button class="btn" onclick="go('gameMenu')">그만하기</button><b>내 초록 판 ${me} / 16</b></div><h1>혼자 하는 판뒤집기</h1><p>분홍 판의 단어를 입력하고 <b>Space</b>를 누르면 즉시 뒤집혀요.</p><div class="board">${g.tiles.map((t,i)=>`<button class="tile ${t.owner}" data-word="${t.w}" onclick="selectTile(${i})" ${t.owner==='me'?'disabled':''}>${t.w}</button>`).join('')}</div>${boardEntry()}<input id="boardInput" class="type-input board-input" aria-label="상대편 단어 입력" placeholder="상대편 단어 입력 후 Space" oncompositionstart="composing=true" oncompositionend="composing=false" oninput="boardType(event)" onkeydown="boardKey(event)"><div class="row" style="justify-content:center;margin-top:18px"><button class="btn mint" onclick="endBoard()">게임 결과 보기</button></div></section>`);setTimeout(()=>$('#boardInput')?.focus(),0)}
function selectTile(i){let g=session.game,target=g.tiles[i].w,input=$('#boardInput');g.active=i;input.value=target;input.classList.remove('error');$('.board-entry').outerHTML=boardEntry(target,target);input.focus();input.setSelectionRange(target.length,target.length);document.querySelectorAll('.board .tile').forEach((el,n)=>el.classList.toggle('active',n===i))}
function updateBoardCandidate(target,value){let preview=$('#boardPreview');if(!preview)return;$('.board-entry').classList.toggle('idle',!value);$('.entry-label').textContent=value?'입력 중인 단어':'바로 입력할 수 있어요';preview.innerHTML=value?sentenceMarkup(target,value):'단어 + Space';$('.board-entry small').textContent=value?'Space를 누르면 바로 판정해요.':'상대편 판의 단어를 입력하고 Space를 누르세요.';document.querySelectorAll('.board .tile').forEach(el=>el.classList.toggle('active',!!value&&el.dataset.word===target))}
function boardType(e){if(composing||e.isComposing)return;let v=e.target.value.trim(),candidates=session.game.tiles.filter(t=>t.owner==='cpu'),candidate=candidates.find(t=>t.w.startsWith(v)&&v)||candidates.find(t=>t.w===v);e.target.classList.remove('error');updateBoardCandidate(candidate?.w||v,v)}
function boardKey(e){if(e.code!=='Space'||composing||e.isComposing)return;e.preventDefault();let value=e.target.value.trim(),tile=session.game.tiles.find(t=>t.owner==='cpu'&&t.w===value);if(!tile)return boardReject(e.target);tile.owner='me';session.game.correct+=tile.w.length;session.game.active=null;if(session.game.tiles.every(x=>x.owner==='me'))return endBoard();renderBoard()}
function boardReject(input){input.classList.add('error');session.game.errors=(session.game.errors||0)+1;let preview=$('#boardPreview');if(preview)preview.innerHTML='<span class="wrong">다시 확인!</span>';input.focus()}
function endBoard(){session.practice={correct:session.game.correct,errors:session.game.errors,start:session.game.start};finish('판뒤집기',{flipped:session.game.tiles.filter(x=>x.owner==='me').length})}
function mouse(){layout(`<div class="section-title"><div><span class="eyebrow">마우스놀이</span><h1>움직이고, 누르고, 옮겨요</h1></div><button class="btn" onclick="go('home')">← 홈</button></div><section class="cards"><button class="card" onclick="clickGame()"><div class="icon">🐻</div><h3>클릭 놀이</h3><p>나타난 동물을 한 번 클릭</p></button><button class="card" onclick="balloonGame()"><div class="icon">🎈</div><h3>풍선 터뜨리기</h3><p>움직이는 풍선을 따라가요</p></button><button class="card" onclick="dragGame()"><div class="icon">🧸</div><h3>드래그 정리</h3><p>물건을 같은 상자로 옮겨요</p></button></section>`)}
function clickGame(){session.mouse={name:'클릭 놀이',count:0,start:Date.now()};clickRound()}function clickRound(){let m=session.mouse;if(m.count>=5)return mouseFinish();let x=10+Math.random()*70,y=10+Math.random()*65;layout(`<section class="panel practice"><h1>동물을 한 번 클릭해요</h1><p>${m.count} / 5 완료</p><div class="game-area"><button class="balloon" aria-label="토끼 클릭" style="left:${x}%;top:${y}%" onclick="session.mouse.count++;clickRound()">🐰</button></div></section>`)}
function balloonGame(){session.mouse={name:'풍선 터뜨리기',count:0,start:Date.now()};balloonRound()}function balloonRound(){if(session.mouse.count>=5)return mouseFinish();let x=8+Math.random()*75,y=6+Math.random()*68;layout(`<section class="panel practice"><h1>풍선을 클릭해 별로 바꿔요</h1><p>${session.mouse.count} / 5 완료</p><div class="game-area"><button class="balloon" aria-label="풍선 터뜨리기" style="left:${x}%;top:${y}%" onclick="session.mouse.count++;balloonRound()">🎈</button></div></section>`)}
function dragGame(){session.mouse={name:'드래그 정리',count:0,start:Date.now()};layout(`<section class="panel practice"><h1>장난감을 상자로 옮겨요</h1><p>장난감을 누른 채 상자 위에서 놓으세요.</p><div class="drop-grid"><div id="toy" class="drag-item" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','toy')">🧸</div><div class="dropzone" ondragover="event.preventDefault()" ondrop="dragDone(event)">📦</div></div><p class="notice">키보드 사용자는 장난감을 선택한 뒤 아래 버튼으로 옮길 수 있어요.</p><button class="btn primary" onclick="dragDone(event)">장난감 상자에 넣기</button></section>`)}function dragDone(e){e.preventDefault?.();session.mouse.count=1;mouseFinish()}function mouseFinish(){let m=session.mouse,sec=Math.max(1,(Date.now()-m.start)/1000);session.practice={correct:m.count,errors:0,start:m.start};finish(m.name,{accuracy:100,cpm:0,completed:m.count,response:(sec/m.count).toFixed(1)})}
function records(refresh=true){let r=state.records.filter(x=>x.studentId===session.student.id);layout(`<div class="section-title"><div><span class="eyebrow">나의 기록</span><h1>조금씩 자라는 중이에요</h1><p class="muted">Supabase에 저장되어 다른 컴퓨터에서도 확인할 수 있어요.</p></div><button class="btn" onclick="go('home')">← 홈</button></div><section class="panel table-wrap">${r.length?`<table class="table"><thead><tr><th>날짜</th><th>활동</th><th>정확도</th><th>타수</th><th>점수</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.date}</td><td>${x.type}</td><td>${x.accuracy}%</td><td>${x.cpm||'-'}</td><td>${x.score}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">첫 연습을 시작해 보세요!</div>`}</section>`);if(refresh)syncStudentRecords().then(()=>records(false)).catch(error=>alert(error.message))}
function settings(){let s=state.settings;layout(`<section class="panel login-box"><span class="eyebrow">설정</span><h1>편안하게 바꿔 보세요</h1><div class="field"><label><input type="checkbox" ${s.sound?'checked':''} onchange="state.settings.sound=this.checked;save()"> 배경음과 효과음 켜기</label></div><div class="field"><label><input type="checkbox" ${s.large?'checked':''} onchange="state.settings.large=this.checked;document.body.style.fontSize=this.checked?'21px':'';save()"> 글자를 크게 보기</label></div><div class="field"><label><input type="checkbox" ${s.reduced?'checked':''} onchange="state.settings.reduced=this.checked;save()"> 움직임 줄이기</label></div><button class="btn primary" onclick="go('home')">설정 완료</button></section>`)}
async function adminLogin(){let pw=prompt('관리자 비밀번호를 입력하세요.');if(!pw)return;try{await recordRequest({action:'verifyAdmin',password:pw});session.adminPassword=pw;session.role='admin';go('admin')}catch(error){alert(error.message)}}
function admin(tab='dash',refresh=true){let rec=state.records,avg=rec.length?Math.round(rec.reduce((a,b)=>a+b.accuracy,0)/rec.length):0;layout(`<div class="section-title"><div><span class="eyebrow">관리자</span><h1>학습 관리 대시보드</h1><p class="muted">모든 컴퓨터의 학습 기록을 Supabase에서 모아 보여줘요.</p></div><button class="btn primary" onclick="addStudent()">+ 학생 등록</button></div><nav class="tabs"><button class="tab ${tab==='dash'?'on':''}" onclick="go('admin','dash')">대시보드</button><button class="tab" onclick="go('students')">학생 관리</button><button class="tab" onclick="go('words')">단어 관리</button></nav><section class="stats"><div class="stat"><strong>${state.students.length}</strong>전체 학생</div><div class="stat"><strong>${rec.filter(x=>x.date==='오늘'||x.date===new Date().toLocaleDateString('ko-KR')).length}</strong>오늘 연습</div><div class="stat"><strong>${avg}%</strong>평균 정확도</div></section><div class="section-title"><h2>최근 활동</h2></div><section class="panel table-wrap"><table class="table"><thead><tr><th>학생</th><th>활동</th><th>정확도</th><th>점수</th></tr></thead><tbody>${rec.slice(0,8).map(x=>`<tr><td>${state.students.find(s=>s.id===x.studentId)?.name||'비활성 학생'}</td><td>${x.type}</td><td>${x.accuracy}%</td><td>${x.score}</td></tr>`).join('')}</tbody></table></section>`);if(refresh)syncAdminRecords().then(()=>admin(tab,false)).catch(error=>alert(error.message))}
function students(){layout(`<div class="section-title"><h1>학생 관리</h1><div class="row"><button class="btn" onclick="go('admin')">← 대시보드</button><button class="btn primary" onclick="addStudent()">+ 학생 등록</button></div></div><section class="panel table-wrap"><table class="table"><thead><tr><th>학교·반</th><th>이름</th><th>동물 비밀번호</th><th>상태</th><th>관리</th></tr></thead><tbody>${state.students.map(s=>`<tr><td>${s.school}<br><span class="muted">${s.room}</span></td><td>${s.name}</td><td>${s.code.map(i=>animals[i][0]).join(' ')}</td><td>${s.active?'활성':'비활성'}</td><td><button class="btn" onclick="toggleStudent(${s.id})">${s.active?'비활성화':'활성화'}</button></td></tr>`).join('')}</tbody></table></section>`)}
function addStudent(){let name=prompt('학생 이름을 입력하세요.');if(!name)return;let room=prompt('반을 입력하세요.','2학년 1반')||'2학년 1반';let used=new Set(state.students.filter(s=>s.room===room).map(s=>s.code.join()));let code;do{code=[...animals.keys()].sort(()=>Math.random()-.5).slice(0,3)}while(used.has(code.join()));state.students.push({id:Date.now(),school:'별빛초등학교',grade:2,room,name,code,active:true});save();students()}function toggleStudent(id){let s=state.students.find(x=>x.id===id);if(confirm(`${s.name} 학생을 ${s.active?'비활성화':'활성화'}할까요?`)){s.active=!s.active;save();students()}}
function words(){layout(`<div class="section-title"><h1>단어 관리</h1><button class="btn" onclick="go('admin')">← 대시보드</button></div><section class="panel"><div class="row"><input id="newWord" class="type-input" style="font-size:18px;text-align:left" maxlength="10" placeholder="새 한글 단어"><button class="btn primary" onclick="addWord()">등록</button></div><div class="cards" style="margin-top:20px">${boardWords.map(w=>`<div class="card"><b>${w}</b><p>쉬움 · 활성</p></div>`).join('')}</div></section>`)}function addWord(){let w=$('#newWord').value.trim();if(!/^[가-힣]{1,10}$/.test(w))return alert('한글 1~10글자로 입력해 주세요.');if(boardWords.includes(w))return alert('이미 있는 단어예요.');boardWords.push(w);words()}
const localLogin=login;
login=function(){if(!sharedReady){layout('<section class="panel login-box"><h1>학생 명단을 불러오는 중이에요…</h1></section>');return loadSharedData().then(login).catch(error=>alert(error.message))}return localLogin()};
studentLogin=async function(){let l=session.login,s=state.students.find(s=>s.school===l.school&&s.room===l.room&&s.name===l.name);if(!s)return alert('학생 정보를 다시 골라 주세요.');try{await dataRequest({action:'verifyStudent',student:{id:s.id,name:s.name,code:l.code}});session.student=s;session.studentCode=[...l.code];session.role='student';go('home')}catch(error){alert(error.message);l.code=[];login()}};
const localHome=home;
home=function(refresh=true){localHome();if(refresh)syncStudentRecords().then(()=>home(false)).catch(()=>{})};
syncStudentRecords=async function(){if(!session.student)return;let pending=state.records.filter(r=>r.studentId===session.student.id&&r.pending);for(let rec of pending){try{await recordRequest({action:'save',student:studentProof(),record:{...rec,details:rec.details||{}}});rec.pending=false}catch{}}let data=await recordRequest({action:'studentRecords',student:studentProof()}),remote=data.records.map(mapRemoteRecord),stillPending=state.records.filter(r=>r.studentId===session.student.id&&r.pending),others=state.records.filter(r=>r.studentId!==session.student.id&&r.pending);state.records=[...remote,...stillPending,...others];save()};
syncAdminRecords=async function(){let data=await dataRequest({action:'adminData',password:session.adminPassword});state.records=data.records.map(mapRemoteRecord);state.students=data.students.map(s=>({...s,id:Number(s.id),code:s.animal_code}));state.schools=(data.schools||[]).map(s=>({...s,id:Number(s.id)}));state.classes=(data.classes||[]).map(c=>({...c,id:Number(c.id),school_id:Number(c.school_id)}));boardWords=data.words;sharedReady=true;save()};
finish=function(type,extra={}){let p=session.practice||{correct:10,errors:0,start:Date.now()-60000},sec=Math.max(10,(Date.now()-p.start)/1000),acc=Math.round(p.correct/(p.correct+p.errors||1)*100),cpm=Math.round(p.correct/sec*60),score=Math.round(acc*5+cpm*2),clientId=globalThis.crypto?.randomUUID?.()||`${session.student.id}-${Date.now()}-${Math.random()}`;let rec={clientId,studentId:session.student.id,type,accuracy:acc,cpm,score,date:'오늘',pending:true,details:extra,...extra};state.records.unshift(rec);save();recordRequest({action:'save',student:studentProof(),record:rec}).then(()=>{rec.pending=false;save()}).catch(()=>alert('기록이 아직 서버에 저장되지 않았어요. 인터넷 연결 후 기록 화면을 열면 다시 저장해요.'));session.last=rec;go('result')};
addStudent=async function(){let name=$('#studentName')?.value.trim(),classroomId=Number($('#studentClass')?.value);if(!name||!classroomId)return alert('학생 이름과 반을 선택해 주세요.');try{let data=await dataRequest({action:'addStudent',password:session.adminPassword,student:{name,classroomId}}),s={...data.student,id:Number(data.student.id),code:data.student.animal_code};state.students.push(s);save();students(s.id)}catch(error){alert(error.message)}};
toggleStudent=async function(id){let s=state.students.find(x=>x.id===id);if(!s||!confirm(`${s.name} 학생을 ${s.active?'비활성화':'활성화'}할까요?`))return;try{let data=await dataRequest({action:'toggleStudent',password:session.adminPassword,id,active:!s.active});s.active=data.student.active;save();students()}catch(error){alert(error.message)}};
addWord=async function(){let w=$('#newWord').value.trim();if(!/^[가-힣]{1,10}$/.test(w))return alert('한글 1~10글자로 입력해 주세요.');if(boardWords.includes(w))return alert('이미 있는 단어예요.');try{let data=await dataRequest({action:'addWord',password:session.adminPassword,word:w});boardWords=data.words;words()}catch(error){alert(error.message)}};
const localStudents=students;
admin=function(tab='dash',refresh=true){let rec=state.records,avg=rec.length?Math.round(rec.reduce((a,b)=>a+b.accuracy,0)/rec.length):0;layout(`<div class="section-title"><div><span class="eyebrow">관리자</span><h1>학습 관리 대시보드</h1><p class="muted">학교, 반, 학생과 모든 학습 기록을 한곳에서 관리해요.</p></div><button class="btn primary" onclick="go('students')">+ 학생 등록</button></div><nav class="tabs"><button class="tab on" onclick="go('admin')">대시보드</button><button class="tab" onclick="go('organizations')">학교·반 관리</button><button class="tab" onclick="go('students')">학생 관리</button><button class="tab" onclick="go('words')">단어 관리</button></nav><section class="stats"><div class="stat"><strong>${state.schools?.length||0}</strong>등록 학교</div><div class="stat"><strong>${state.classes?.length||0}</strong>등록 반</div><div class="stat"><strong>${state.students.length}</strong>전체 학생</div><div class="stat"><strong>${avg}%</strong>평균 정확도</div></section><div class="section-title"><h2>최근 활동</h2></div><section class="panel table-wrap"><table class="table"><thead><tr><th>학생</th><th>활동</th><th>정확도</th><th>점수</th></tr></thead><tbody>${rec.slice(0,8).map(x=>`<tr><td>${roomText(state.students.find(s=>s.id===x.studentId)?.name||'비활성 학생')}</td><td>${roomText(x.type)}</td><td>${x.accuracy}%</td><td>${x.score}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">아직 학습 기록이 없어요.</td></tr>'}</tbody></table></section>`);if(refresh)syncAdminRecords().then(()=>admin(tab,false)).catch(error=>alert(error.message))};
function adminTabs(active){return `<nav class="tabs"><button class="tab ${active==='dash'?'on':''}" onclick="go('admin')">대시보드</button><button class="tab ${active==='org'?'on':''}" onclick="go('organizations')">학교·반 관리</button><button class="tab ${active==='student'?'on':''}" onclick="go('students')">학생 관리</button><button class="tab ${active==='word'?'on':''}" onclick="go('words')">단어 관리</button></nav>`}
function organizations(){let schools=state.schools||[],classes=state.classes||[];layout(`<div class="section-title"><div><span class="eyebrow">관리자</span><h1>학교·반 관리</h1><p class="muted">학교를 먼저 등록하고, 그 학교에 반을 만들어 주세요.</p></div><button class="btn" onclick="go('admin')">← 대시보드</button></div>${adminTabs('org')}<section class="admin-form-grid"><form class="panel" onsubmit="addSchoolFromForm(event)"><div class="admin-form-icon">🏫</div><h2>학교 등록</h2><div class="field"><label for="schoolName">학교 이름</label><input id="schoolName" maxlength="80" placeholder="예: 별빛초등학교" required></div><button class="btn primary" type="submit">학교 등록하기</button></form><form class="panel" onsubmit="addClassFromForm(event)"><div class="admin-form-icon">🏷️</div><h2>반 등록</h2><div class="field"><label for="classSchool">학교</label><select id="classSchool" required><option value="">학교 선택</option>${schools.map(s=>`<option value="${s.id}">${roomText(s.name)}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label for="classGrade">학년</label><select id="classGrade" required>${[1,2,3,4,5,6].map(n=>`<option value="${n}">${n}학년</option>`).join('')}</select></div><div class="field"><label for="className">반 이름</label><input id="className" maxlength="40" placeholder="예: 1반" required></div></div><button class="btn mint" type="submit" ${schools.length?'':'disabled'}>반 등록하기</button></form></section><section class="panel table-wrap admin-list"><h2>등록 현황</h2><table class="table"><thead><tr><th>학교</th><th>등록된 반</th></tr></thead><tbody>${schools.map(s=>`<tr><td><b>${roomText(s.name)}</b></td><td><div class="class-chips">${classes.filter(c=>c.school_id===s.id).map(c=>`<span>${c.grade}학년 ${roomText(c.name)}</span>`).join('')||'<span class="muted">아직 등록된 반이 없어요.</span>'}</div></td></tr>`).join('')||'<tr><td colspan="2" class="empty">첫 학교를 등록해 주세요.</td></tr>'}</tbody></table></section>`)}
async function addSchoolFromForm(event){event.preventDefault();let name=$('#schoolName').value.trim();if(!name)return;try{let data=await dataRequest({action:'addSchool',password:session.adminPassword,name});state.schools.push({...data.school,id:Number(data.school.id)});save();organizations()}catch(error){alert(error.message)}}
async function addClassFromForm(event){event.preventDefault();let classroom={schoolId:Number($('#classSchool').value),grade:Number($('#classGrade').value),name:$('#className').value.trim()};try{let data=await dataRequest({action:'addClass',password:session.adminPassword,classroom});state.classes.push({...data.classroom,id:Number(data.classroom.id),school_id:Number(data.classroom.school_id)});save();organizations()}catch(error){alert(error.message)}}
function updateStudentClasses(){let schoolId=Number($('#studentSchool')?.value),select=$('#studentClass');if(!select)return;select.innerHTML='<option value="">반 선택</option>'+state.classes.filter(c=>c.school_id===schoolId&&c.active).map(c=>`<option value="${c.id}">${c.grade}학년 ${roomText(c.name)}</option>`).join('')}
students=function(newStudentId){if(state.students.some(s=>!Array.isArray(s.code))){layout('<section class="panel"><h1>학생 명단을 불러오는 중이에요…</h1></section>');return syncAdminRecords().then(()=>students()).catch(error=>alert(error.message))}let schools=state.schools||[],newStudent=state.students.find(s=>s.id===newStudentId);layout(`<div class="section-title"><div><span class="eyebrow">관리자</span><h1>학생 관리</h1><p class="muted">등록할 학교와 반을 고르면 동물 비밀번호가 자동으로 만들어져요.</p></div><button class="btn" onclick="go('admin')">← 대시보드</button></div>${adminTabs('student')}${newStudent?`<section class="password-ticket"><div><span>새 학생 등록 완료</span><h2>${roomText(newStudent.name)}의 동물 비밀번호</h2><p>학생에게 아래 순서를 알려 주세요.</p></div><div class="ticket-code">${newStudent.code.map(i=>animalAvatar(i,'ticket')).join('')}</div><button class="btn" onclick="navigator.clipboard?.writeText('${newStudent.code.join('-')}');this.textContent='복사했어요!'">번호 복사</button></section>`:''}<section class="panel student-register"><h2>학생 등록</h2><div class="student-form"><div class="field"><label for="studentSchool">학교</label><select id="studentSchool" onchange="updateStudentClasses()"><option value="">학교 선택</option>${schools.map(s=>`<option value="${s.id}">${roomText(s.name)}</option>`).join('')}</select></div><div class="field"><label for="studentClass">반</label><select id="studentClass"><option value="">반 선택</option></select></div><div class="field"><label for="studentName">학생 이름</label><input id="studentName" maxlength="30" placeholder="예: 김민준" onkeydown="if(event.key==='Enter'){event.preventDefault();addStudent()}"></div><button class="btn primary" onclick="addStudent()">학생 등록 · 비밀번호 자동 생성</button></div></section><section class="panel table-wrap admin-list"><table class="table"><thead><tr><th>학교·반</th><th>이름</th><th>동물 비밀번호</th><th>상태</th><th>관리</th></tr></thead><tbody>${state.students.map(s=>`<tr><td>${roomText(s.school)}<br><span class="muted">${s.grade}학년 ${roomText(s.room)}</span></td><td><b>${roomText(s.name)}</b></td><td><div class="table-animal-code">${s.code.map(i=>animalAvatar(i,'tiny')).join('')}</div></td><td><span class="status-dot ${s.active?'active':''}">${s.active?'활성':'비활성'}</span></td><td><button class="btn" onclick="toggleStudent(${s.id})">${s.active?'비활성화':'활성화'}</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">등록된 학생이 없어요.</td></tr>'}</tbody></table></section>`)};
function logout(){session={student:null,studentCode:null,adminPassword:null,role:null,login:{school:'',room:'',name:'',code:[]}};go('start')}
loadSharedData().catch(()=>{});start();
